config/routes.rb
Rails.application.routes.draw do
  
	root "welcome#index"
	devise_for :students

	resources :courses
	resources :semesters
	resources :activitys
end

app/views/layouts/_nav_with_student.html.erb
<div class="mdl-layout--large-screen-only">
	<a href="" class="mdl-navigation__link color-information">Logado como <%= current_student.name %></a>
</div>
<div class="text-center mdl-layout--small-screen-only">
	<a href="" class="mdl-navigation__link">Logado como <%= current_student.name %></a>
</div>
<%= link_to "Cursos", courses_path, class: "mdl-button mdl-button--raised  mdl-button--accent mdl-layout--large-screen-only" %> 
<%= link_to "Sair", destroy_student_session_path, method: :delete, class: "mdl-button mdl-button--accent mdl-layout--large-screen-only" %> 
<%= link_to "Cursos", courses_path, class: "mdl-button mdl-layout--small-screen-only" %>
<%= link_to "Sair", destroy_student_session_path, method: :delete, class: "mdl-button mdl-layout--small-screen-only" %>

app/views/layouts/_nav_without_student.html.erb
<%= link_to "Entrar", new_student_session_path, class: "mdl-navigation__link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app" lang="pt-BR">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" hred="<%= asset_url 'drawers.png' %>">
    <title>GAVETA</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-red.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  </head>

  <body class="mdl-layout mdl-js-layout mdl-layout--fixed-header" >

    <header class="mdl-layout__header transparent-header">
      <div class="mdl-layout__header-row">
        <%= image_tag "drawers.png", class: "mdl-layout-icon" %>
        <%= link_to "GAVETA", root_path, class: "mdl-title not-link font-title" %>

        <div class="mdl-layout-spacer"></div>

        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <%= nav_content %>
        </nav>
      </div>
    </header>

    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
      <span class="mdl-layout-title font-title">GAVETA</span>
        <nav class="mdl-navigation">
          <%= nav_content %>
        </nav>
    </div>

    <main class="mdl-layout__content">
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--1-col mdl-layout--medium-screen-only"></div>
        <div class="mdl-cell mdl-cell--10-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <%= yield %>
          <div id="toast">
            <div class="mdl-snackbar__text">
            </div>
          </div>
        </div>
    </div>
    </main>
    <footer class="text-center">
      <small>Desenvolvido por <a target="_blank" href="https://www.facebook.com/llleonardolll">Leonardo Camp</a> - leofrederiche@gmail.com</small>
    </footer>
  </body>
</html>